### ISSUE TITLE
JS errors in IE11 with Magepack

### ISSUE THREAD

**Issue by markusbehrens** [magesuite/magepack#109]
In one of our shops running on Magento 2.4.1 we are getting a lot of JS errors in IE11 on PV pages about invalid characters & syntax errors when Magepack is enabled. With Magepack disabled all JS works fine. Is Magepack not compatible with IE11? I could not find anything about compatibility anywhere.

**Comment by krzksz** [comment]
Hey, Magepack is mainly concatenating files and it should be generating
valid ES5 code.

Can you maybe try generating bundles without minification and pinpoint
exact fragment of code that IE has problems with?

wt., 15 cze 2021, 14:35 użytkownik Markus Behrens ***@***.***>
napisał:

**Comment by markusbehrens** [comment]
Hey, thanks for the quick answer!

We get for example an "invalid character" error in bundle-common.js on this code, which originally comes from "parallax.js" in magezon/pagebuilder extension:

`transform: `translateX(${ itemX }px) translateY(${ itemY }px) translateZ(0)`,`

looks like it does not like the "`" character. but when running without Magepack it just works.

When I replace all "`" characters with """ in bundle-common.js, I get a syntax error about this code, also originally coming from "parallax.js":

```
var throttledParallaxMouseRun = throttle( 200, ( x, y, deviceOrientation ) => {
	    parallaxMouseRun( x, y, deviceOrientation );
	});
```

Additionally it throws an error like "Unable to get property 'noConflict' of undefined or null reference" from "_cache/merged/ac4b81b6bc2ec9d537989d1e796ef862.js" in  this code (I have no idea where this file is coming from).

```
require(['jquery'], function ($) {
    'use strict';

    $.noConflict();
});
```

**Comment by krzksz** [comment]
Alright, the code you provided along with those backticks is the newer
version of JS specification and shouldn't work on IE either way.

I don't know the extension that you are using and how they handle loading
of those newer files so you need to try to debug it yourself or manually
exclude it from being bundled.

As to the other errors I wouldn't focus on them before resolving the above
issue.

wt., 15 cze 2021, 15:09 użytkownik Markus Behrens ***@***.***>
napisał:

**Comment by krzksz** [comment]
You can also contact the extension provider that their JavaScript is not
compatible with older browsers and show them fragments of code that you
provided here.

wt., 15 cze 2021, 15:14 użytkownik Mateusz Krzeszowiak ***@***.***>
napisał:

**Comment by markusbehrens** [comment]
true that arrow function expressions are ES6 and should not work in IE11. I have no idea why there are no errors thrown when Magepack is disabled, maybe they do some special loading. will have to investigate further, thanks a lot for your help!

**Comment by markusbehrens** [comment]
I just figured out the invalid characters error in parallax.js also occurs when not using Magepack. but it does not prevent other JS elements to be loaded then. so I wonder if actually the "_cache/merged/ac4b81b6bc2ec9d537989d1e796ef862.js" file is the real culprit here, because that only gets loaded when using magepack and then other JS elements on the page are not loaded. is that file generated by Magepack?

**Comment by krzksz** [comment]
No, this file is generated by Magento and contains all JS files defined in
HEAD. You can try disabling JavaScript files merging as a workaround but
the performance may be a bit worse so I wouldn't treat it as an ultimate
solution.

wt., 15 cze 2021, 15:54 użytkownik Markus Behrens ***@***.***>
napisał:

**Comment by markusbehrens** [comment]
you are right, the file is generated by Magento when merge JS files is enabled, that option was always enabled together with enabling magapack on my system, that's why I thought it might be related. but I tested those options separately and was able to break down the issue now, it is definitely that code from magezon pagebuilder which breaks in IE and stops loading all other code from bundle-common.js, so no JS works any more. without magepack it is just one file (parallax.js) that stops working, all other JS still works fine. so we will contact magezon about IE compatibility and exclude parallax.js from magepack.config.js as a workaround, until a fix is provided. thanks again for your help!
