### ISSUE TITLE
Looking for option to minify bundle when Magento minification is off

### ISSUE THREAD

**Issue by Quinten** [magesuite/magepack#110]
Hi,

We have used magepack bundling successfully in the past, but are now experiencing problems in the backend when we turn on the minification of Magento. To mitigate this we have turned off minification in Magento, but this also means the bundle is not minified anymore. Is there an option to also minify the bundles with terser even when the Magento minification is turned off?

Kind regards

**Comment by krzksz** [comment]
Hey, there is no option for that but nothing stops you from minifying
generated bundles using terser CLI yourself as an additional step after
bundling.

czw., 24 cze 2021, 16:49 użytkownik Quinten Clause ***@***.***>
napisał:

**Comment by Quinten** [comment]
You are right... I'll give that a try then...
