### ISSUE TITLE
Bug: some javascript don't income in the bundle

### ISSUE THREAD

**Issue by sgeleon** [magesuite/magepack#116]
Hi. 

### Preconditions 
Some javascript don't income in the bundle

### Steps to reproduce 
1) I added a link on the javascript to the default.xml 
![image](https://user-images.githubusercontent.com/18437080/129182986-ff66bf03-365f-45cd-9ce7-1f94b97ec3fc.png)
2) Generated bundle (magepack generate --cms-url="{{CMS_PAGE_URL}}" --category-url="{{CATEGORY_PAGE_URL}}" --product-url="{{PRODUCT_PAGE_URL}}"
3) Make bundle  (magepack bundle)
4) Enable module MageSuite_Magepack (bin/magento config:set dev/js/enable_magepack_js_bundling 1)
5) Cleare cache (bin/magento cache:clean)

### Expected result 
Javascript file income to the bundle

### Actual result 
Some javascript files don't income to the bundle.
![image](https://user-images.githubusercontent.com/18437080/129184431-b0bbc5c3-baf7-48e8-8486-ee65268a2517.png)

**Comment by krzksz** [comment]
Hey, thanks for a detailed information about the issue that you are having, that's super helpful!

From the contents of the file it looks like you're adding a regular script that only requests dependencies from RequireJS but does not register by itself. Additionally, the way that you define it (in XML) will make Magento merge it with other critical JS when JS merging is enabled in the admin (and it should be for best performance).

You can refer to https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/javascript/js_init.html for explanation on how to add extra JS to the page _The Magento 2 Way_, with that Magepack should catch it no problem.

**Comment by sgeleon** [comment]
Thank you for your response. It's helped me.

**Comment by sgeleon** [comment]
Hi @krzksz

Please add it to the readme for more clarity. 

For included all JS files included by RequireJS,  execute this command:

```
bin/magento config:set dev/js/merge_files 1
```
