### ISSUE TITLE
There are many html files added to the bundle config

### ISSUE THREAD

**Issue by UglyBuglyX** [magesuite/magepack#117]
Hi,
I am using magepack in one of my projects and I noticed that there are many html files added to the magepack.config.js for the checkout bundle. 
So I would like to ask you is it possible to combine html files or it's a bug?

**Comment by krzksz** [comment]
Hey!
It's a feature, Magepack bundles UI Comonents' templates which normally
have to be downloaded for them to render.

czw., 19 sie 2021, 15:16 użytkownik UglyBuglyX ***@***.***>
napisał:

**Comment by kanevbg** [comment]
Interested to know too. @krzksz is there any docs on how it works?

**Comment by krzksz** [comment]
Magento bundles [RequireJS text plugin](https://github.com/requirejs/text), which lets you request text files through it. This is either defined directly in components dependencies (search for `text!` prefix in their name) or via `template` property in UI Components. When this is the case, such file is treated just as any other JS dependency and needs to be downloaded before component can be initialized.

Magepack works by collecting and concatenating all of the dependencies and modules needed on a certain page to a single file, that's it. You can learn a bit more by watching my presentation about it: https://www.youtube.com/watch?v=ahxoTedqHjw
