### ISSUE TITLE
Request: Ignore TLS errors

### ISSUE THREAD

**Issue by vbuck** [magesuite/magepack#12]
This came about as a result of troubleshooting a different issue: #6. In that issue, I made a comment, which points to my fork:

- https://github.com/magesuite/magepack/issues/6#issuecomment-611283619
- https://github.com/vbuck/magepack/blob/feature/chrome-no-sandbox-flag/lib/generate.js#L14

You'll see that in addition to `--no-sandbox` I'm also calling for `ignoreHTTPSErrors`. As this is a build tool, I see little reason to care for live-environment exposure and restrictions. Assuming this would run in a containerized environment during build phases of a deployment, it seems reasonable to ignore any TLS errors.

As a point of interest, I've just opened a PR to support Magepack for Warden. See here:

- https://github.com/davidalger/warden/pull/138
- https://github.com/davidalger/warden/pull/138/files#diff-963ebcb54e3862ce2b136c92d04ff2e5R10

Right now I'm referencing my fork to get the benefits of ignored TLS errors. If we can support this officially, I can change my proposal for Warden to use your official package.

**Comment by krzksz** [comment]
Released in 2.3.0

**Comment by krzksz** [comment]
Hey @vbuck please let me know if that solved  the issue, it's great to see Magepack getting wider adoption.

**Comment by vbuck** [comment]
@krzksz I can confirm this solved my problem. See this commit on the related project:

- https://github.com/davidalger/warden/pull/138/commits/bef0ef7a1f2b70cfc9f53305d748d67e58d7c1ca

Thanks for making this update.
