### ISSUE TITLE
Doesn't work on Magento 2.4.3

### ISSUE THREAD

**Issue by FY0u11** [magesuite/magepack#134]
Did everything like described in Readme. Bundles being created but still on the frontend in network I see 200+ requests to the JS files

![2022-01-22_19-49](https://user-images.githubusercontent.com/48677295/150641036-3aceaff5-34f8-4014-8626-3993fd76dba4.png)

**Comment by igorwulff** [comment]
I can confirm it is working on 2.4.3-p1. Are you sure you don't have enabled js advanced bundling in your Magento environment and cleared caches? Also can you confirm there were no JS errors on the pages while generating the magepack config, etc?
