### ISSUE TITLE
Terser Minify-Error: Unexpected token: punc (.)

### ISSUE THREAD

**Issue by p24-max** [magesuite/magepack#155]
The command `magepack bundle --minify -d` fails with the following error:

```
[...]
Loading "Magento_PageBuilder/js/content-type/banner/appearance/default/widget" from "pub/static/frontend/Babyonline/theme/de_DE/Magento_PageBuilder/js/content-type/banner/appearance/default/widget.js".
› Bundle "category" collected.                                                                                                                              17:29:06
› Minifying "category" bundle.                                                                                                                              17:29:06

 ERROR  Unexpected token: punc (.)                                                                                                                          17:29:06

  at ne (node_modules/terser/dist/bundle.min.js:1:19592)
  at c (node_modules/terser/dist/bundle.min.js:1:28298)
  at l (node_modules/terser/dist/bundle.min.js:1:28389)
  at f (node_modules/terser/dist/bundle.min.js:1:28442)
  at U (node_modules/terser/dist/bundle.min.js:1:42256)
  at me (node_modules/terser/dist/bundle.min.js:1:48326)
  at node_modules/terser/dist/bundle.min.js:1:49206
  at ve (node_modules/terser/dist/bundle.min.js:1:49221)
  at ke (node_modules/terser/dist/bundle.min.js:1:50475)
  at We (node_modules/terser/dist/bundle.min.js:1:50707)
```

When I execute the command without `--minify` option, it works well. Any idea how to fix this?

**Comment by dejanangelevski** [comment]
i have the same issue, any solution?

**Comment by musabatas** [comment]
Same here.

**Comment by DinkoIlicic** [comment]
The issue should be tied to https://www.javascripttutorial.net/es-next/javascript-optional-chaining-operator/ if some new module uses the new javascript feature, the magepack does not properly read it.

This should be fixed by updating the terser package to the newest version which is done here:
https://github.com/magesuite/magepack/commit/b96eeccd3605d6fcfac8d4cc26445c3b0072990f
This is merged into the master branch but no release yet for it for us to use.

**Comment by jakegore** [comment]
Do we know when b96eeccd3605d6fcfac8d4cc26445c3b0072990f is going to be in a release? @krzksz

**Comment by sanganinamrata** [comment]
@krzksz May I know when the fixes of this issue will get released? We're facing that issue on our live websites, and need to disable bundling due to that. The solution needed urgently.

**Comment by akshayshakya94** [comment]
I'm also facing same issue. please help

**Comment by hammockvienna** [comment]
same here... would be great if there is a new release ...
