### ISSUE TITLE
cms pages allows generate zero items

### ISSUE THREAD

**Issue by AlaaL** [magesuite/magepack#156]
When using magepack generate on our site it generate items for product, category, checkout, common, but nothing for cms.
This is the command I am using 

`>magepack  generate --cms-url="https://lelas.net/tr/" --category-url="https://lelas.net/tr/prime-collection.html" --product-url="https://lelas.net/tr/fancy-fence-eau-de-parfum-55-ml-1.html" --debug`

I also tried without locale like `https://lelas.net` and tried another cms page like contact us or privacy policy it gives the same result.

![image](https://user-images.githubusercontent.com/5410074/193467723-2f1e8e88-90e7-4fee-b05e-c686369403d3.png)

**Comment by Quazz** [comment]
For most CMS pages all the JS they use will be in "common". (loaded on every page)

CMS bundle is JS found only on CMS pages.
