### ISSUE TITLE
Feature Request - Allow --cms-url to appear multiple times on command line

### ISSUE THREAD

**Issue by gwharton** [magesuite/magepack#16]
Allow --cms-url to appear multiple times on command line and combine the results from all cms pages visited into the single cms group.

I don't see a reason why product and category should be specified multiple times as these are more static.

**Comment by gwharton** [comment]
Typical use case would be where a store has several different cms areas which load different javascript content. e.g home page, information pages, contact us, all could potentially load different things. I guess one resolution would be to change the store so that all javascript content is loaded for all cms pages using layout changes, as ultimately its all going to be bundled into one cms bundle, but still. would save alot of work to be able to specify multiple cms pages to crawl.

**Comment by elfeffe** [comment]
I think there shoukld be infinite "extra" pages, cms or any other module page that needs to be crawled

**Comment by gwharton** [comment]
> I think there shoukld be infinite "extra" pages, cms or any other module page that needs to be crawled

Yeah, just allow --cms-page to be included infinite number of times on the command line. Each entry gets crawled and added to the cms bundle.

**Comment by roma-glushko** [comment]
Seems to be related to https://github.com/magesuite/magepack/issues/21

**Comment by heldchen** [comment]
this should be true also for product-urls, as different product types can result in different additional js libs loaded.
