### ISSUE TITLE
puppeteer@2.1.1: < 18.1.0 is no longer supported

### ISSUE THREAD

**Issue by tudn9x** [magesuite/magepack#174]
Hi magesuite team,

I install  npm install -g magepack and it show error and I can't run magepack.
Please help

Thank you very much

**Comment by fredden** [comment]
@tudn9x what does the error message say? What version of `magepack` did you install? What version of NodeJS are you running?

**Comment by tudn9x** [comment]
Thank you @fredden 

I used magepack version 2.11.2, nodejs version 18 and npm version 8

<img width="997" alt="image" src="https://user-images.githubusercontent.com/4941829/210312867-a9259451-5631-4768-ae47-43c14a34a53e.png">

**Comment by fredden** [comment]
@tudn9x thanks for confirming. I can see a warning, but no errors. What's not working for you?

**Comment by tudn9x** [comment]
@fredden Thank you very much.
I think it's working now. I'm not sure, It didn't work yesterday.
