### ISSUE TITLE
Exclude js file

### ISSUE THREAD

**Issue by matteobaro** [magesuite/magepack#24]
Hello,
Great module, works great better than baler...

i have a problem with a module slider that has problem with building
It is possibile to exclude some js file of a module from building?

Thanks

**Comment by matteobaro** [comment]
ok i have found the solution
just remove the js file from magepack config

Thanks alot great module

**Comment by torhoehn** [comment]
Had the same with a slider module, but want to find a solution to get it working instead of excluding it from the bundle.

```
/**
 * Initialization widget for slider
 *
 * @method resizeBanner
 */
define([
    'jquery',
    'uikit!slideshow'
], function($, UIkit) {
    "use strict";
```

Could it be something with the ! in the define statement?
