### ISSUE TITLE
Issues with magepack generate

### ISSUE THREAD

**Issue by idaninadal** [magesuite/magepack#34]
magepack generate --cms-url="https://glomania.com/" --category-url="https://www.glomania.com/paints.html" --product-url="https://www.glomania.com/hydrochromic-water-reactive-ink.html"

This keeps working with no end?

With --debug option I see errors in console.

Does it need a clean JS without any errors?

**Comment by denistrator** [comment]
what is the console output you get after running `magepack generate`?

**Comment by idaninadal** [comment]
I was able to make it run after fixing the js errors.  Then I moved rhe generated file from local to server sice the chromium driver had missing dependencies on nexcess. I ran all steps and installed the patches for Magento 2.3.4. 
Enabled magepack bundling and deployed content then did magepack bundle and it did add files in pub/static but my frontend was all brocken with complex je errors from requirejs modules saying define is incorrect and so. 
I will try this on staging coz this is not a very stable road to production yet. 
How can I get support for this?
