### ISSUE TITLE
bundle-common.min.js loading TWICE

### ISSUE THREAD

**Issue by adrianbsystems** [magesuite/magepack#35]
All seems to be working good, except bundle-common.min.js seems to be loading twice , how can we fix this? thanks

![Bundle-loading-twice](https://user-images.githubusercontent.com/26751722/86176125-6703c480-bb1c-11ea-99ab-1427eb686c61.JPG)

**Comment by krzksz** [comment]
Hey, this is actually the intended behaviour as each bundle gets prefetched before it is requested by RequireJS so that the code gets available earlier. If you uncheck the `Disable cache` button you'll be able to see that the file is downloaded only once.
