### ISSUE TITLE
Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by HirokazuNishi** [magesuite/magepack#4]
I tried to run magepack against my local docker environment, but got title's error message.
Is it possible to disable timeout or expand? Or any other nice solution to solve this?

Here is my environment:

- Magento Open Source 2.3.4
- MageSuite 3.x
- MageSuite-MagePack 1.0.x
- PHP 7.3
- production mode (just for testing magepack)

**Comment by krzksz** [comment]
Hey, are you sure Magepack is able to even reach the server? You can try running it with `--debug` command which will run Chrome in normal, non-headless mode.

In general, on my local environment and full page cache enabled 30s were always plenty so maybe the problem is somewhere else.

**Comment by krzksz** [comment]
Oh and you don't actually need MageSuite to use Magepack, only its single Magento package.

**Comment by HirokazuNishi** [comment]
Of course, magepack could reach my dev env. It stuck on checkout stage.
I'm building MageSuite based M2 website now, that's why it's necessary for our project ;)

**Comment by krzksz** [comment]
That's really cool! Can you confirm that there are no JavaScript errors in the checkout normally? How much time is needed for each of the cart and checkout to be fully loaded? Also, it may be helpful to attach an error stack trace so I can see which stage hangs.

**Comment by HirokazuNishi** [comment]
Finally I finished. Disabling xdebug was necessary.
