### ISSUE TITLE
Modularisation

### ISSUE THREAD

**Issue by edward-simpson** [magesuite/magepack#47]
Would it be possible to modularise magepack?  Splitting out the generation and bundle tasks into separate modules would be helpful for us as magepack gets installed as part of our deployment pipeline, we only use the generate command locally, so it would be really helpful if we could reduce bulk in deployments as chromium takes a while to download each time

**Comment by krzksz** [comment]
Hey @edward-simpson! Since Puppeteer that requires Chromium is an optional dependency, you should be able to just get away with `npm install --no-optional` during your deployment.
