### ISSUE TITLE
How to Set up MagePack with Multiple Website ?

### ISSUE THREAD

**Issue by pankaj-pareek** [magesuite/magepack#49]
Hello All, 

I am facing issue to set up Mage Pack in Multi Website Instance. As we need to run the below command:

magepack generate --cms-url="http://WEBSITE1_URL/" --category-url="http://WEBSITE1_URL/category.html" --product-url="http://WEBSITE1_URL/product.html" 

Also is there any documentation, How we can set up this on Magento Commerce Cloud Platform ?

Thanks

**Comment by robeka** [comment]
We are running into the same issue. Is this multi website compatible?

**Comment by maderlock** [comment]
Short answer - it works safely with multiple websites, but not optimally.

Longer version - We run this with multiple websites, but have to make do with the fact that there is only going to be a single set of pages investigated. However, bundling (not generation) is done per theme, so it will bundle what is relevant per theme. The closer the themes are on your websites, the better the bundling will work.

We raised this need for different source pages for different themes in #30

**Comment by slackerzz** [comment]
> Also is there any documentation, How we can set up this on Magento Commerce Cloud Platform ?

@pankaj-pareek you need to modify the build hook in `.magento.app.yaml`. The default build hook is:
```yaml
hooks:
    # We run build hooks before your application has been packaged.
    build: |
        set -e
        php ./vendor/bin/ece-tools build:generate
        php ./vendor/bin/ece-tools build:transfer
```

You need to install node js and then generare the bundle:
```yaml
hooks:
    # We run build hooks before your application has been packaged.
    build: |
        set -e

        unset NPM_CONFIG_PREFIX
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh"  ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts=erbium
        npm install -g magepack

        php ./vendor/bin/ece-tools build:generate

        echo "Generating magepack bundle..."
        magepack bundle

        php ./vendor/bin/ece-tools build:transfer
```

**Comment by krzksz** [comment]
Good news! Thanks to @Igloczek contribution we now have an option to select themes matching certain glob to bundle which means you can just run it multiple times with separate configs for each website.
