### ISSUE TITLE
Js error in bundle file

### ISSUE THREAD

**Issue by cuong-tran-solteq** [magesuite/magepack#54]
First of all thanks a lot for your amazing work, I give a shot for Magepack since I need a solution for bundling and Baler doesn't seem that much mature for me.  It does what I need to create a bundle file and reduce payload. However, I got this issue and I haven't got any idea what could cause it

**Preconditions**

Install Magento2.3.5-p2, applied patch for mixins.js

**Steps to reproduce**

I installed magepack, run generate command, deployed static content, magepack bundle, clean cache.
One thing I found that there is some error in prod which may affect the crawling of megapack (is it?)
`googleads.g.doubleclick.net/pagead/id:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.doubleclick.net/instream/ad_status.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`

**Expected result**

No JS errors

**Actual result**
bundle-common.js:formatted:65103 Uncaught TypeError: define(...) is not a function from this part

`(function(factory) {
    if (typeof define === 'function' && define.amd) {
        define('jquery/jquery.metadata', ["jquery"], factory);
    } else {
        factory(jQuery);
    }
}(function($) {

    $.extend({
        metadata: {
            defaults: {
                type: 'class',
                name: 'metadata',
                cre: /({.*})/,
                single: 'metadata',
                meta: 'validate'
            },
            setType: function(type, name) {
                this.defaults.type = type;
                this.defaults.name = name;`

**Comment by krakencorals** [comment]
I tried magepack today also, i got the same error as above. coupled with a checkout that didnt work as compareVersions wasnt defined

**Comment by cuong-tran-solteq** [comment]
@krzksz Could you please have a look at that issue if it is possible to workaround?

**Comment by gwharton** [comment]
I had to patch with https://github.com/magento/magento2/pull/27690 aswell as the main mixins patch. This is merged into 2.4-develop, but is not in 2.4.0

**Comment by cuong-tran-solteq** [comment]
Thanks, @gwharton I will check that patch also. Let's see if that works in my case.
