### ISSUE TITLE
tell please, support 2.4.1 ?

### ISSUE THREAD

**Issue by sarootua** [magesuite/magepack#61]

**Comment by delyriand** [comment]
Hi @sarootua,

Do you have a problem with version 2.4.1?
I have tried magepack with this version and have not encountered any issues.

BR.

**Comment by jtomaszewski** [comment]
BTW question for those who made it work under 2.4.x - is the patch for `mixins.js` (that the README and this PR https://github.com/magento/baler/issues/23 speaks about) is still needed ? This repo https://github.com/integer-net/magento2-requirejs-bundling says it's not on Magento >= 2.3.6, so curious if I have to do something. (We're running 2.4.1. )

**Comment by gaiterjones** [comment]
@jtomaszewski I have tested with 2.4.1 and did use any patches.

**Comment by erfanimani** [comment]
Magepack is running fine under 2.4.1 here.

Without more info from OP I suggest the ticket to be closed.
