### ISSUE TITLE
magepack generate hanging

### ISSUE THREAD

**Issue by matt-grech** [magesuite/magepack#65]
I am running 'magepack generate' along with parameters but it hangs when collecting modules for bundle cms. I have run this on the ubuntu web server holding Magento 2, and also on my local windows PC. All are running the latest version on Ubuntu and Nodejs

**Comment by digiltd** [comment]
Try adding `--debug` to the end of the command, it will open a Chromium browser so you can see what is going on. We have this trouble, it is usually a js error in the site itself or something that requires user input. The debug will help.

**Comment by mlavelas** [comment]
Same issue here. In my case the user is not able to purchase if is not logged in. I've enabled purchase for not logged in users, ran the command with --debug option and it opens two windows. One of them loads the category URL, the other one is always blank.
The terminal shows:
Collecting bundle modules in the browser.
Collecting modules for bundle "category".

And nothing else...

I don't see what is causing the hang.

Anyway, if I must run this command on production server I cannot enable purchase for not logged in users there, so an option to pass a user/pass would be useful.

**Comment by stephenaldworth** [comment]
I'm finding this happening for me too, but only when using a theme different from the original that comes with Magento 2. I'm trying to get it to work with Porto theme.

**Comment by birdman002** [comment]
Sometimes its a 3rd party call that gets stuck it seems like
