### ISSUE TITLE
Ajax loader stucked checkout

### ISSUE THREAD

**Issue by sajen87** [magesuite/magepack#75]
Hi Guys, 

On Mageno 2.3 (patche from https://github.com/cweagans/composer-patches installed).
I had a quite a lot issues with loader/spinner stucked, first one was at category page. But the most painless and most sensitive is at the checkout, both steps unfortunately. I manage to remove div form onepage.html:
  ` <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>`
Then another after I was going to billing/payment step. 
I'm using also bluepayment widget for some payment methods, and during the tests, another stucked loader at blik payment come up. I believe it's something `$.ajax({ showLoader: true`. 
Also there's no errors in console :/ Which is more difficult to resolve by me. 
Guys is there any chance to help with me with this issue, please?? 
Thanks, 
Pawel

**Comment by mborkowski** [comment]
Hi @sajen87,
So removing loader will not help. It doesn't disappear for some reason, most likely some ajax requests fail, so for 99% cases it should be logged into console. Maybe you have filtered out some types of output in your dev tools?

**Comment by webstudioswest** [comment]
I am having the same issue on a Magento 2.3.6 setup. Seems that on any site I have that is using a 3rd party checkout module and not the native Magento checkout I get this infinite loader. Would be amazing if there was a way to configure this to ignore certain parts of the system such as checkout, or to specifically allow certain scripts to be included outside the bundle like these 3rd party modules for checkout.

**Comment by gaiterjones** [comment]
For anyone experiencing problems with bundling at the checkout pages a real easy solution is to _disable_ bundling for all checkout pages.

If you look at the `isEnabled` method in the Block\BundlesLoader class this determines whether the magepack module is enabled and if bundling should be activated. Simply detect the checkout page here and return false to disable bundling at checkout...

If you require login to place an order you could also detect if the user is logged in and only bundle for not logged in users...

**Comment by cristianmattar** [comment]
I need to disable checkout and put my isEnabled like this:
    public function isEnabled()
    {
        return $this->scopeConfig->isSetFlag(
            self::XML_PATH_ENABLE_MAGEPACK_BUNDLING,
            ScopeInterface::SCOPE_STORE
        );
        if ($this->request->getFullActionName() == 'checkout_index_index){
 
            // disable for checkout
            return false;
        }
    }
But, the checkout continues to be optimized

**Comment by mborkowski** [comment]
Thank you guys for providing a workaround for this strange issue. We were not aware of that since in any our projects (and we have a couple of them already running) we didn't encounter anything like this. I'm closing this issue. If, however, somebody will struggle with something similar and above workaround won't help - feel free to reopen. Thanks once again!

**Comment by luksurious** [comment]
We faced a similar issue when trying to integrate Magepack.

After some research, it turned out that [HC-Sticky](https://github.com/somewebmedia/hc-sticky) broke the checkout which was included in common.
When we exclude this library, things work fine.

**Comment by sebfie** [comment]
I also has this issue without any error in console. So strange....

**Comment by AlaaL** [comment]
> We faced a similar issue when trying to integrate Magepack.
> 
> After some research, it turned out that [HC-Sticky](https://github.com/somewebmedia/hc-sticky) broke the checkout which was included in common. When we exclude this library, things work fine.

How did you excluded it ?

**Comment by AlaaL** [comment]
I am facing the same issue and the above solutions doesn't seem to work

**Comment by MagePsycho** [comment]
> > We faced a similar issue when trying to integrate Magepack.
> > After some research, it turned out that [HC-Sticky](https://github.com/somewebmedia/hc-sticky) broke the checkout which was included in common. When we exclude this library, things work fine.
> 
> How did you excluded it ?

If you just remove the entry from `magepack.config.js` it will be excluded.
