### ISSUE TITLE
bash: magepack: command not found (generate command)

### ISSUE THREAD

**Issue by nandopsilva** [magesuite/magepack#77]
Hello!

When I execute the generate command it returns the following error:

bash: magepack: command not found

=============================================

Centos7.9

node: v14.15.4

yarn: 1.22.5

npm: 6.14.10

"creativestyle/magesuite": "^7.0.0",
"creativestyle/magesuite-magepack": "^1.1",
"creativestyle/theme-creativeshop": "^11.0.0",

Kind Regards,
Fernando Silva

**Comment by krzksz** [comment]
Hey, it seems like a problem with your system and not Magepack. Please make sure that directory with npm globally installed packages is in your PATH.
