### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ia-gaurav** [magesuite/magepack#78]
i am getting below error on centos : 

{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/magepack/node_modules/puppeteer/.local-chromium'

**Comment by haiacom** [comment]
see this https://github.com/magesuite/magepack/issues/8

**Comment by krzksz** [comment]
Hey, this seems to be a problem with permissions to your global node_modules directory, not strictly connected with Magepack. Please see mentioned issue or try Googling for `Error: EACCES: permission denied, mkdir '/usr/lib/node_modules`.
