### ISSUE TITLE
Help with total number of js call after bundling

### ISSUE THREAD

**Issue by ia-gaurav** [magesuite/magepack#81]
i have enabled bundling , but still i can not get score of 80 plus in google page speed.

Please let us know how many js will be there after bundling - as i 3 js call on page after bundling 

**For category listing page i see :**

1.  /magepack/bundle-common.min.js
2.  magepack/bundle-category.min.js
3.  _cache/merged/c4d97dcdfde25e4bcc37deab165590ed.min.js

is it fine ? should 2 js be called there instead of 3 now

**Comment by krzksz** [comment]
It looks proper, 3 requests is as good as it gets when you have bundling enabled. As to the score - well, there are multiple factors that go into it other then JavaScript like server response time, size of CSS, lazyloading of images etc. which you can try to improve but I don't think any Magento customization can get perfect 100.
